{% set name = "pypolar" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypolar-{{ version }}.tar.gz
  sha256: d4734cdf9ed18b85fd87a6f59f57a0268371d240b05d2cf13c4b3bd598a3d38e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - sympy
    - scipy
    - pytest
    - pyyaml

test:
  imports:
    - pypolar
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  source_files:
    - tests/test_jones.py
    - tests/test_stokes.py
  commands:
    - pip check
    - pytest tests/test_jones.py
    - pytest tests/test_stokes.py

about:
  home: https://github.com/scottprahl/pypolar.git
  summary: Python module for polarizers and birefringent elements with support for ellipsometry.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://pypolar.readthedocs.io/
  dev_url: https://github.com/scottprahl/pypolar

extra:
  recipe-maintainers:
    - scottprahl
